### ISSUE TITLE
Error on trying to get brazilian flag

### ISSUE THREAD

**Issue by bdlukaa** [LunaGao/flag_flutter#10]
Error:

``════════ Exception caught by SVG ═══════════════════════════════════════════════
The following StateError was thrown resolving a single-frame picture stream:
Bad state: Expected to find Drawable with id url(#O).
Have ids: (url(#D), url(#E), url(#e), url(#G))

When the exception was thrown, this was the stack
#0      DrawableDefinitionServer.getDrawable 
package:flutter_svg/src/vector_drawable.dart:577
#1      _Elements.use 
package:flutter_svg/…/svg/parser_state.dart:184
#2      SvgParserState.parse 
package:flutter_svg/…/svg/parser_state.dart:776
<asynchronous suspension>
#3      SvgParser.parse 
package:flutter_svg/parser.dart:14
...
Picture provider: ExactAssetPicture(name: "packages/flag/res/flag/br.svg", bundle: null, colorFilter: null)
Picture key: AssetBundlePictureKey(bundle: PlatformAssetBundle#12a7a(), name: "packages/flag/res/flag/br.svg", colorFilter: null)
════════════════════════════════════════════════════════════════════════════════´´

I tried to add other flags (AB and US) and they work perfectly, but the brazilian flag isn't working

**Comment by LunaGao** [comment]
![image](https://user-images.githubusercontent.com/5066920/80821736-e6077a00-8c0b-11ea-939d-9943e46a476d.png)
Fixed in 2.0.3.

But there is still a bug, you can see that the letters are still a bit abnormal.

**Comment by LunaGao** [comment]
Create a issue on flutter_svg repo. 
https://github.com/dnfield/flutter_svg/issues/337

**Comment by LunaGao** [comment]
fixed in v6.0.0
