### ISSUE TITLE
Slovakian flag is not displayed

### ISSUE THREAD

**Issue by strigePC** [LunaGao/flag_flutter#12]
When I try to display Slovakian flag using the `Flag.getFlag(country: 'sk', height: 20, width: 20)`, I get the following error:

════════ Exception caught by SVG ════════════════════════════════════
The following UnimplementedError was thrown in parseSvgElement:
The <style> element is not implemented in this library.

Style elements are not supported by this library and the requested SVG may not render as intended.

If possible, ensure the SVG uses inline styles and/or attributes (which are supported), or use a preprocessing utility such as svgcleaner to inline the styles for you.

Picture key: AssetBundlePictureKey(bundle: PlatformAssetBundle#f676f(), name: "packages/flag/res/flag/sk.svg", colorFilter: null)
══════════════════════════════════════════════════════════════

Flutter: `v1.17.0`
Dart: `v2.8.1`
Device: `OnePlus 7T Android 10`
Package version: `flag v2.0.3`

**Comment by LunaGao** [comment]
fixed in 2.0.4
