### ISSUE TITLE
Exception when drawing Argentinian flag 

### ISSUE THREAD

**Issue by AKhashi** [LunaGao/flag_flutter#15]
I/flutter (14497): ══╡ EXCEPTION CAUGHT BY SVG ╞═══════════════════════════════════════════════════════════════════════
I/flutter (14497): The following StateError was thrown resolving a single-frame picture stream:
I/flutter (14497): Bad state: Expected to find Drawable with id url(#uppalpebra).
I/flutter (14497): Have ids: (url(#rays), url(#ray1), url(#ray2), url(#loweyecontour))
I/flutter (14497): 
I/flutter (14497): When the exception was thrown, this was the stack:
I/flutter (14497): #0      DrawableDefinitionServer.getDrawable (package:flutter_svg/src/vector_drawable.dart:577:7)
I/flutter (14497): #1      _Elements.use (package:flutter_svg/src/svg/parser_state.dart:184:34)
I/flutter (14497): #2      SvgParserState.parse (package:flutter_svg/src/svg/parser_state.dart:776:26)
I/flutter (14497): <asynchronous suspension>
I/flutter (14497): #3      SvgParser.parse (package:flutter_svg/parser.dart:14:60)
I/flutter (14497): #4      Svg.fromSvgString (package:flutter_svg/svg.dart:110:25)
I/flutter (14497): #5      Svg.svgPictureStringDecoder (package:flutter_svg/svg.dart:72:36)
I/flutter (14497): #6      SvgPicture.svgStringDecoder.<anonymous closure> (package:flutter_svg/svg.dart:531:15)
I/flutter (14497): #7      AssetBundlePictureProvider._loadAsync (package:flutter_svg/src/picture_provider.dart:457:19)
I/flutter (14497): <asynchronous suspension>
I/flutter (14497): #8      AssetBundlePictureProvider.load (package:flutter_svg/src/picture_provider.dart:435:43)
I/flutter (14497): #9      PictureProvider.resolve.<anonymous closure>.<anonymous closure> (package:flutter_svg/src/picture_provider.dart:327:17)
I/flutter (14497): #10     PictureCache.putIfAbsent (package:flutter_svg/src/picture_cache.dart:67:22)
I/flutter (14497): #11     PictureProvider.resolve.<anonymous closure> (package:flutter_svg/src/picture_provider.dart:325:16)
I/flutter (14497): #12     SynchronousFuture.then (package:flutter/src/foundation/synchronous_future.dart:41:29)
I/flutter (14497): #13     PictureProvider.resolve (package:flutter_svg/src/picture_provider.dart:322:24)
I/flutter (14497): #14     _SvgPictureState._resolveImage (package:flutter_svg/svg.dart:641:10)
I/flutter (14497): #15     _SvgPictureState.didChangeDependencies (package:flutter_svg/svg.dart:615:5)
I/flutter (14497): #16     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:4661:12)
I/flutter (14497): #17     ComponentElement.mount (package:flutter/src/widgets/framework.dart:4476:5)
I/flutter (14497): ...     Normal element mounting (28 frames)
I/flutter (14497): #45     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3446:14)
I/flutter (14497): #46     Element.updateChild (package:flutter/src/widgets/framework.dart:3214:18)
I/flutter (14497): #47     _ListTileElement._mountChild (package:flutter/src/material/list_tile.dart:1000:30)
I/flutter (14497): #48     _ListTileElement.mount (package:flutter/src/material/list_tile.dart:1014:5)
I/flutter (14497): ...     Normal element mounting (200 frames)
I/flutter (14497): #248    Element.inflateWidget (package:flutter/src/widgets/framework.dart:3446:14)
I/flutter (14497): #249    MultiChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:5947:32)
I/flutter (14497): ...     Normal element mounting (57 frames)
I/flutter (14497): #306    Element.inflateWidget (package:flutter/src/widgets/framework.dart:3446:14)
I/flutter (14497): #307    Element.updateChild (package:flutter/src/widgets/framework.dart:3214:18)
I/flutter (14497): #308    SliverMultiBoxAdaptorElement.updateChild (package:flutter/src/widgets/sliver.dart:1162:36)
I/flutter (14497): #309    SliverMultiBoxAdaptorElement.createChild.<anonymous closure> (package:flutter/src/widgets/sliver.dart:1147:20)
I/flutter (14497): #310    BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2607:19)
I/flutter (14497): #311    SliverMultiBoxAdaptorElement.createChild (package:flutter/src/widgets/sliver.dart:1140:11)
I/flutter (14497): #312    RenderSliverMultiBoxAdaptor._createOrObtainChild.<anonymous closure> (package:flutter/src/rendering/sliver_multi_box_adaptor.dart:354:23)
I/flutter (14497): #313    RenderObject.invokeLayoutCallback.<anonymous closure> (package:flutter/src/rendering/object.dart:1866:58)
I/flutter (14497): #314    PipelineOwner._enableMutationsToDirtySubtrees (package:flutter/src/rendering/object.dart:918:15)
I/flutter (14497): #315    RenderObject.invokeLayoutCallback (package:flutter/src/rendering/object.dart:1866:13)
I/flutter (14497): #316    RenderSliverMultiBoxAdaptor._createOrObtainChild (package:flutter/src/rendering/sliver_multi_box_adaptor.dart:343:5)
I/flutter (14497): #317    RenderSliverMultiBoxAdaptor.insertAndLayoutChild (package:flutter/src/rendering/sliver_multi_box_adaptor.dart:489:5)
I/flutter (14497): #318    RenderSliverList.performLayout.advance (package:flutter/src/rendering/sliver_list.dart:219:19)
I/flutter (14497): #319    RenderSliverList.performLayout (package:flutter/src/rendering/sliver_list.dart:262:19)
I/flutter (14497): #320    RenderObject.layout (package:flutter/src/rendering/object.dart:1767:7)
I/flutter (14497): #321    RenderSliverEdgeInsetsPadding.performLayout (package:flutter/src/rendering/sliver_padding.dart:135:11)
I/flutter (14497): #322    RenderSliverPadding.performLayout (package:flutter/src/rendering/sliver_padding.dart:375:11)
I/flutter (14497): #323    RenderObject.layout (package:flutter/src/rendering/object.dart:1767:7)
I/flutter (14497): #324    RenderViewportBase.layoutChildSequence (package:flutter/src/rendering/viewport.dart:452:13)
I/flutter (14497): #325    RenderViewport._attemptLayout (package:flutter/src/rendering/viewport.dart:1444:12)
I/flutter (14497): #326    RenderViewport.performLayout (package:flutter/src/rendering/viewport.dart:1353:20)
I/flutter (14497): #327    RenderObject.layout (package:flutter/src/rendering/object.dart:1767:7)
I/flutter (14497): #328    RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:111:13)
I/flutter (14497): #329    RenderObject.layout (package:flutter/src/rendering/object.dart:1767:7)
I/flutter (14497): #330    RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:111:13)
I/flutter (14497): #331    RenderObject.layout (package:flutter/src/rendering/object.dart:1767:7)
I/flutter (14497): #332    RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:111:13)
I/flutter (14497): #333    RenderObject.layout (package:flutter/src/rendering/object.dart:1767:7)
I/flutter (14497): #334    RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:111:13)
I/flutter (14497): #335    RenderObject.layout (package:flutter/src/rendering/object.dart:1767:7)
I/flutter (14497): #336    RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:111:13)
I/flutter (14497): #337    RenderObject.layout (package:flutter/src/rendering/object.dart:1767:7)
I/flutter (14497): #338    RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:111:13)
I/flutter (14497): #339    RenderObject.layout (package:flutter/src/rendering/object.dart:1767:7)
I/flutter (14497): #340    RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:111:13)
I/flutter (14497): #341    RenderObject.layout (package:flutter/src/rendering/object.dart:1767:7)
I/flutter (14497): #342    RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:111:13)
I/flutter (14497): #343    RenderObject.layout (package:flutter/src/rendering/object.dart:1767:7)
I/flutter (14497): #344    RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:111:13)
I/flutter (14497): #345    RenderObject.layout (package:flutter/src/rendering/object.dart:1767:7)
I/flutter (14497): #346    RenderFlex.performLayout (package:flutter/src/rendering/flex.dart:808:17)
I/flutter (14497): #347    RenderObject.layout (package:flutter/src/rendering/object.dart:1767:7)
I/flutter (14497): #348    MultiChildLayoutDelegate.layoutChild (package:flutter/src/rendering/custom_layout.dart:171:11)
I/flutter (14497): #349    _ScaffoldLayout.performLayout (package:flutter/src/material/scaffold.dart:484:7)
I/flutter (14497): #350    MultiChildLayoutDelegate._callPerformLayout (package:flutter/src/rendering/custom_layout.dart:240:7)
I/flutter (14497): #351    RenderCustomMultiChildLayoutBox.performLayout (package:flutter/src/rendering/custom_layout.dart:399:14)
I/flutter (14497): #352    RenderObject.layout (package:flutter/src/rendering/object.dart:1767:7)
I/flutter (14497): #353    RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:111:13)
I/flutter (14497): #354    RenderObject.layout (package:flutter/src/rendering/object.dart:1767:7)
I/flutter (14497): #355    RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:111:13)
I/flutter (14497): #356    _RenderCustomClip.performLayout (package:flutter/src/rendering/proxy_box.dart:1248:11)
I/flutter (14497): #357    RenderObject.layout (package:flutter/src/rendering/object.dart:1767:7)
I/flutter (14497): #358    RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:111:13)
I/flutter (14497): #359    RenderObject.layout (package:flutter/src/rendering/object.dart:1767:7)
I/flutter (14497): #360    RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:111:13)
I/flutter (14497): #361    RenderObject.layout (package:flutter/src/rendering/object.dart:1767:7)
I/flutter (14497): #362    RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:111:13)
I/flutter (14497): #363    RenderObject.layout (package:flutter/src/rendering/object.dart:1767:7)
I/flutter (14497): #364    RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:111:13)
I/flutter (14497): #365    RenderObject.layout (package:flutter/src/rendering/object.dart:1767:7)
I/flutter (14497): #366    RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:111:13)
I/flutter (14497): #367    RenderObject.layout (package:flutter/src/rendering/object.dart:1767:7)
I/flutter (14497): #368    RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:111:13)
I/flutter (14497): #369    RenderObject.layout (package:flutter/src/rendering/object.dart:1767:7)
I/flutter (14497): #370    RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:111:13)
I/flutter (14497): #371    RenderObject.layout (package:flutter/src/rendering/object.dart:1767:7)
I/flutter (14497): #372    RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:111:13)
I/flutter (14497): #373    RenderOffstage.performLayout (package:flutter/src/rendering/proxy_box.dart:3225:13)
I/flutter (14497): #374    RenderObject.layout (package:flutter/src/rendering/object.dart:1767:7)
I/flutter (14497): #375    _RenderTheatre.performLayout (package:flutter/src/widgets/overlay.dart:700:15)
I/flutter (14497): #376    RenderObject.layout (package:flutter/src/rendering/object.dart:1767:7)
I/flutter (14497): #377    RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:111:13)
I/flutter (14497): #378    RenderObject.layout (package:flutter/src/rendering/object.dart:1767:7)
I/flutter (14497): #379    RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:111:13)
I/flutter (14497): #380    RenderObject.layout (package:flutter/src/rendering/object.dart:1767:7)
I/flutter (14497): #381    RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:111:13)
I/flutter (14497): #382    RenderObject.layout (package:flutter/src/rendering/object.dart:1767:7)
I/flutter (14497): #383    RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:111:13)
I/flutter (14497): #384    RenderObject.layout (package:flutter/src/rendering/object.dart:1767:7)
I/flutter (14497): #385    RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:111:13)
I/flutter (14497): #386    RenderObject.layout (package:flutter/src/rendering/object.dart:1767:7)
I/flutter (14497): #387    RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:111:13)
I/flutter (14497): #388    RenderObject.layout (package:flutter/src/rendering/object.dart:1767:7)
I/flutter (14497): #389    RenderView.performLayout (package:flutter/src/rendering/view.dart:167:13)
I/flutter (14497): #390    RenderObject._layoutWithoutResize (package:flutter/src/rendering/object.dart:1630:7)
I/flutter (14497): #391    PipelineOwner.flushLayout (package:flutter/src/rendering/object.dart:887:18)
I/flutter (14497): #392    RendererBinding.drawFrame (package:flutter/src/rendering/binding.dart:402:19)
I/flutter (14497): #393    WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:884:13)
I/flutter (14497): #394    RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:284:5)
I/flutter (14497): #395    SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1113:15)
I/flutter (14497): #396    SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:1052:9)
I/flutter (14497): #397    SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:968:5)
I/flutter (14497): #401    _invoke (dart:ui/hooks.dart:261:10)
I/flutter (14497): #402    _drawFrame (dart:ui/hooks.dart:219:3)
I/flutter (14497): (elided 3 frames from dart:async)
I/flutter (14497): 
I/flutter (14497): Picture provider: ExactAssetPicture(name: "packages/flag/res/flag/ar.svg", bundle: null,
I/flutter (14497):   colorFilter: null)
I/flutter (14497): Picture key: AssetBundlePictureKey(bundle: PlatformAssetBundle#0f783(), name:
I/flutter (14497):   "packages/flag/res/flag/ar.svg", colorFilter: null)
I/flutter (14497): ════════════════════════════════════════════════════════════════════════════════════════════════════

**Comment by Flucadetena** [comment]
Having the same issue in 6.0.0:

```
Bad state: Expected to find Drawable with id url(#d).
Have ids: (url(#flag-icons-ar), url(#c), url(#a), url(#b), url(#h))

When the exception was thrown, this was the stack
#0      DrawableDefinitionServer.getDrawable
package:flutter_svg/src/vector_drawable.dart:579
#1      _Elements.use
package:flutter_svg/…/svg/parser_state.dart:212
#2      SvgParserState.parse
package:flutter_svg/…/svg/parser_state.dart:885
<asynchronous suspension>
#3      SvgParser.parse
package:flutter_svg/parser.dart:27
<asynchronous suspension>
#4      Svg.fromSvgString
package:flutter_svg/svg.dart:139
<asynchronous suspension>
#5      Svg.svgPictureStringDecoder
package:flutter_svg/svg.dart:90
<asynchronous suspension>
Picture provider: ExactAssetPicture(name: "packages[/flag/res/4x3/ar.svg]()", bundle: null, colorFilter: null)
Picture key: AssetBundlePictureKey(bundle: PlatformAssetBundle#d5189(), name: "packages[/flag/res/4x3/ar.svg]()", colorFilter: null, theme: SvgTheme(currentColor: null, fontSize: 14.0, xHeight: 7.0))
```
