### ISSUE TITLE
getMiniFlag for Malaysia flag returns the wrong flag

### ISSUE THREAD

**Issue by lvlzeros** [LunaGao/flag_flutter#2]
Hi,

getMiniFlag returns the wrong Malaysia flag.

Malaysia flag should've 14-pointed stars, 3red-3white long stripes beneath the blue section.

Attached below is the example of corrected Malaysia flag. However I'm not able to get the SVG format exported as in the svg2 folder.
[my.zip](https://github.com/LunaGao/flag_flutter/files/4176910/my.zip)

Need your help to fix this. Thank you!

**Comment by LunaGao** [comment]
Thanks @lvlzeros .
