### ISSUE TITLE
Conflict with new version of flutter_svg 

### ISSUE THREAD

**Issue by alr2413** [LunaGao/flag_flutter#25]
Hi, 
Thanks for providing this package, here is my issue with the latest version of flutter:

"Because flag 3.0.1 depends on flutter_svg ^0.17.4 and no versions of flag match >3.0.1 <4.0.0, flag ^3.0.1 requires flutter_svg ^0.17.4."

**Comment by dluksza** [comment]
This also prevents from using this library with flutter 1.20.0-7.2.pre

**Comment by LunaGao** [comment]
Latest version of flutter_svg (0.18.0) is not using the stable channel of Flutter SDK.

**Comment by LunaGao** [comment]
Fixed in `3.0.2-pre` release.
