### ISSUE TITLE
Error: Flutter version 1.20.0

### ISSUE THREAD

**Issue by bytestreme** [LunaGao/flag_flutter#31]
I have build errors on **Flutter (Channel stable, 1.20.0)**

```
Error: Type 'DiagnosticableMixin' not found.
Error: Type 'DiagnosticableMixin' not found
Error: The type 'DiagnosticableMixin' can't be mixed in
Error: Superclass has no method named 'debugFillProperties'
Error: Superclass has no method named 'debugFillProperties'
```

Those errors come from **flutter_svg: ^0.17.4** when used with this version of Flutter

I am using the following to fix this:

`dependency_overrides:
  flutter_svg: 0.18.0
`

Solution:

Upgrade **flag** package's **flutter_svg** dependency version to  **0.18.0**

**Comment by LunaGao** [comment]
@bytestreme Which version of flag_flutter are you using ?

**Comment by bytestreme** [comment]
> @bytestreme Which version of flag_flutter are you using ?

`3.0.4` version

**Comment by LunaGao** [comment]
Thanks @simonpham 's PR. Merged into `stable` branch.
