### ISSUE TITLE
Sound null safety

### ISSUE THREAD

**Issue by bdlukaa** [LunaGao/flag_flutter#37]
Do you plan to migrate the project to sound null safety?

https://dart.dev/null-safety

**Comment by LunaGao** [comment]
https://pub.dev/packages/flag/versions/4.0.0-nullsafety

**Comment by silkyland** [comment]
> https://pub.dev/packages/flag/versions/4.0.0-nullsafety

Seen not working I temporary use 
`
flag: 
    git: https://github.com/dluksza/flag_flutter.git
`
