### ISSUE TITLE
Web not working - path not found

### ISSUE THREAD

**Issue by leoshusar** [LunaGao/flag_flutter#41]
I'm trying to use this package for web app and I am getting an exception, that path doesn't exist:

```
The following ProgressEvent$ object was thrown resolving an image codec:
  [object ProgressEvent]

When the exception was thrown, this was the stack
Image provider: NetworkImage("packages/flag/res/flag/cz.svg", scale: 1)
Image key: NetworkImage("packages/flag/res/flag/cz.svg", scale: 1)
```

When I run it using `flutter run -d chrome`, I can find those icons in `assets/packages/flag/res/flag/` - starting with `assets`.
However when I run it using VS Code debugging (F5), neither of those paths exist.

I am using Flutter beta version 1.25.0-8.1.pre.

**Comment by LunaGao** [comment]
fixed in 3.2.1
