### ISSUE TITLE
Proposal: Use the ISO 3166-1 alpha-2 specification for the list of flags

### ISSUE THREAD

**Issue by maxstevens-nl** [LunaGao/flag_flutter#52]
Currently, this library contains flags of states that are UN members, complemented by a couple of other flags which belong to disputed or undisputed territories. However, at this point, the addition of these territories seem arbitrary.

To prevent any discussion that may arise in the future about the addition of a certain flag, and to add around 50 territories which are currently missing from this library, I propose the list of [ISO 3166-1 alpha-2](https://en.wikipedia.org/wiki/ISO_3166-1_alpha-2) country codes to be used to define the body of countries and territories included in this library.

The ISO 3166-1 alpha-2 specification seems to be the de facto standard that defines countries and territories. It comprises all the countries which are currently included in the library and will add around 50 more, although some of them will not have associated flags.

**Comment by LunaGao** [comment]
I understand and agree with you.
Regarding whether to add certain regions, it is not just a simple coding issue in many cases.
The original purpose of this library was just for developers to easily obtain the required flag. Maybe the ISO 3166-1-alpha-2 you proposed is a good solution.
Thank you very much for this suggestion. I will continue to investigate this aspect based on ISO 3166-1-alpha-2 to find a suitable solution.

**Comment by LunaGao** [comment]
fixed in v6.0.0
