### ISSUE TITLE
flutter-web: ImageCodecException: Failed to decode image data. Image source: http://localhost:61608/assets/packages/flag/res/flag/us.svg

### ISSUE THREAD

**Issue by jakusb** [LunaGao/flag_flutter#54]
I run into this error: ImageCodecException: Failed to decode image data. Image source: http://localhost:61608/assets/packages/flag/res/flag/us.svg when using Flag('en') and running on MacOs debug mode in Chrome.
![image](https://user-images.githubusercontent.com/9477833/122902782-10a41d00-d34f-11eb-8a1b-78f5ad97a061.png)

This works fine in iOS.

Opening the link also works fine and shows the American flag

Using   flag: ^5.0.0-nullsafety

**Comment by LunaGao** [comment]
It should be solved by this issue: https://github.com/LunaGao/flag_flutter/issues/49
