### ISSUE TITLE
Maybe add a flag for english language that is 50% American and 50% Britain to indicate English language

### ISSUE THREAD

**Issue by jakusb** [LunaGao/flag_flutter#55]
I use this package to show the language selected in the App.
A shared flag US/UK would be nice to be able to show, so maybe add a hybrid flag?

**Comment by JiangHongTiao** [comment]
If this gets implemented, I think it would be better to implement it in more abstract way as combination of any two/multiple flags, not necessarily us/uk. Exceptions may cause problems in the future and complicate maintenance.

**Comment by LunaGao** [comment]
fixed in v6.0.0
