### ISSUE TITLE
List web as supported platform

### ISSUE THREAD

**Issue by alexeyinkin** [LunaGao/flag_flutter#59]
Currently the page at pub.dev lists Android, iOS, Linux, MacOS and Windows as supported platforms. However the issue #41 suggests that web works as well. Can you list it as a supported platform?

I am adding web for my app and I try to sort out packages that do not support it to replace them. This should be achievable by looking at tops of pub.dev pages alone.

**Comment by LunaGao** [comment]
Done with flag version 5.0.2
