### ISSUE TITLE
Countries with missing flags

### ISSUE THREAD

**Issue by pytong** [LunaGao/flag_flutter#6]
Please add these countries to your list:

South Africa
South Georgia and the South Sandwich Islands
Nepal
Oman
Sri Lanka
Isle of Man
Serbia
Cayman Islands
Dominica, Commonwealth of
Grenada
Haiti
American Samoa
Argentina
Brazil
Falkland Islands (Malvinas)
Peru

Thanks!  :)

**Comment by RaistlinTAO** [comment]
And Taiwan as well, thanks

**Comment by LunaGao** [comment]
fixed in #7

**Comment by LunaGao** [comment]
All countries came from UN website.
