### ISSUE TITLE
Still getting problems similar to those described by issue #44.

### ISSUE THREAD

**Issue by psills2410** [LunaGao/flag_flutter#60]
Issue #44 was reported as fixed on Feb 19, but I still get very similar messages:

======== Exception caught by SVG ===================================================================
The following UnimplementedError was thrown in parseSvgElement:
The <style> element is not implemented in this library.

Style elements are not supported by this library and the requested SVG may not render as intended.

If possible, ensure the SVG uses inline styles and/or attributes (which are supported), or use a preprocessing utility such as svgcleaner to inline the styles for you.

Picture key: AssetBundlePictureKey(bundle: PlatformAssetBundle#f8196(), name: "packages/flag/res/flag/ki.svg", colorFilter: null)
====================================================================================================

======== Exception caught by SVG ===================================================================
The following UnimplementedError was thrown in parseSvgElement:
The <style> element is not implemented in this library.

Style elements are not supported by this library and the requested SVG may not render as intended.

If possible, ensure the SVG uses inline styles and/or attributes (which are supported), or use a preprocessing utility such as svgcleaner to inline the styles for you.

Picture key: AssetBundlePictureKey(bundle: PlatformAssetBundle#f8196(), name: "packages/flag/res/flag/mo.svg", colorFilter: null)
====================================================================================================
I/flutter ( 9950): unhandled element metadata; Picture key: AssetBundlePictureKey(bundle: PlatformAssetBundle#f8196(), name: "packages/flag/res/flag/xk.svg", colorFilter: null)
I/flutter ( 9950): unhandled element sodipodi:namedview; Picture key: AssetBundlePictureKey(bundle: PlatformAssetBundle#f8196(), name: "packages/flag/res/flag/xk.svg", colorFilter: null)
I/flutter ( 9950): Warning: Flutter SVG only supports the following formats for `width` and `height` on the SVG root:
I/flutter ( 9950):   width="100%"
I/flutter ( 9950):   width="100px"
I/flutter ( 9950):   width="100" (where the number will be treated as pixels).
I/flutter ( 9950): The supplied value (756.13pt) will be discarded and treated as if it had not been specified.
I/flutter ( 9950): Warning: Flutter SVG only supports the following formats for `width` and `height` on the SVG root:
I/flutter ( 9950):   width="100%"
I/flutter ( 9950):   width="100px"
I/flutter ( 9950):   width="100" (where the number will be treated as pixels).
I/flutter ( 9950): The supplied value (504.09pt) will be discarded and treated as if it had not been specified.

**Comment by LunaGao** [comment]
fixed in v6.0.0
