### ISSUE TITLE
Cannot push to repo some small changes

### ISSUE THREAD

**Issue by philiposD** [LunaGao/flag_flutter#65]
Hi, I wanted to push a fix because I've noticed that there are some problems with the countries like **Scotland gb-sct, Wales gb-wls**  etc. there are not mapped and cannot address it with enum. 
Also, the files should be renamed with an underscore to list them in enum **GB_SCT**.

When I want to push I'm getting:
```
ERROR: Permission to LunaGao/flag_flutter.git denied to philiposD.
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
```

**Comment by LunaGao** [comment]
You should request a PR when you want to merge any code into the repo.

**Comment by philiposD** [comment]
Well, I cannot create a new pull request because I cannot push by a new branch with my changes.
In the meanwhile, I've made an overwrite in my local project but it would be ok to have it fixed, I already have the changes prepared.
I also noticed that the Argentina flag has some problems with having multiple IDs inside the SVG  file and it's not showing.
```lang-dart
Bad state: Expected to find Drawable with id url(#d).
Have ids: (url(#flag-icons-ar), url(#c), url(#a), url(#b), url(#h))

When the exception was thrown, this was the stack: 
#0      DrawableDefinitionServer.getDrawable (package:flutter_svg/src/vector_drawable.dart:579:7)
#1      _Elements.use (package:flutter_svg/src/svg/parser_state.dart:212:34)
#2      SvgParserState.parse (package:flutter_svg/src/svg/parser_state.dart:885:26)
<asynchronous suspension>
#3      SvgParser.parse (package:flutter_svg/parser.dart:27:12)
<asynchronous suspension>
#4      Svg.fromSvgString (package:flutter_svg/svg.dart:139:12)
<asynchronous suspension>
#5      Svg.svgPictureStringDecoder (package:flutter_svg/svg.dart:90:34)
<asynchronous suspension>
Picture provider: ExactAssetPicture(name: "packages/flag/res/4x3/ar.svg", bundle: null, colorFilter: null)
```

**Comment by philiposD** [comment]
So the problem was that I was doing it from the main project, not from a forked one 🙈
I have create a PR: https://github.com/LunaGao/flag_flutter/pull/68
