### ISSUE TITLE
Can't find United Kingdom Flag

### ISSUE THREAD

**Issue by standingmind** [LunaGao/flag_flutter#66]
It would be better to have Country Name as comment in flag code. 
I can't find United Kingdom flag.

**Comment by LunaGao** [comment]
I'm not sure, is `FlagsCode.GB` the `United Kingdom flag` ?

**Comment by stargazeastro** [comment]
same issue

**Comment by davidCpp16** [comment]
> I'm not sure, is `FlagsCode.GB` the `United Kingdom flag` ?

Yes `FlagsCode.GB` is the United Kingdom flag!
