### ISSUE TITLE
[Version: 6.0.0] Failed to find definition for #a

### ISSUE THREAD

**Issue by KamleshArya** [LunaGao/flag_flutter#67]
Following exceptions are coming after upgrading to new version: 6.0.0

════════ Exception caught by SVG ═══════════════════════════════════════════════
The following assertion was thrown while parsing AssetBundlePictureKey(bundle: PlatformAssetBundle#0d224(), name: "packages/flag/res/4x3/mx.svg", colorFilter: null, theme: SvgTheme(currentColor: null, fontSize: 16, xHeight: 8)) in radialGradient:
Failed to find definition for #a

This library only supports <defs> and xlink:href references that are defined ahead of their references.

This error can be caused when the desired definition is defined after the element referring to it (e.g. at the end of the file), or defined in another file.

This error is treated as non-fatal, but your SVG file will likely not render as intended

**Comment by LunaGao** [comment]
Which platform you are using? Android, iOS, or Web?

**Comment by KamleshArya** [comment]
Its happening in both Android, Flutter-Web @LunaGao . Dint tried with iOS
