### ISSUE TITLE
Exception when drawing Peru flag

### ISSUE THREAD

**Issue by Flucadetena** [LunaGao/flag_flutter#69]
════════ Exception caught by SVG ═══════════════════════════════════════════════
The following StateError was thrown resolving a single-frame picture stream:
Bad state: Expected to find Drawable with id url(#c).
Have ids: (url(#flag-icons-pe), url(#g), url(#d), url(#a), url(#b), url(#e), url(#f))

When the exception was thrown, this was the stack
#0      DrawableDefinitionServer.getDrawable
package:flutter_svg/src/vector_drawable.dart:579
#1      _Elements.use
package:flutter_svg/…/svg/parser_state.dart:212
#2      SvgParserState.parse
package:flutter_svg/…/svg/parser_state.dart:885
<asynchronous suspension>
#3      SvgParser.parse
package:flutter_svg/parser.dart:27
<asynchronous suspension>
#4      Svg.fromSvgString
package:flutter_svg/svg.dart:139
<asynchronous suspension>
#5      Svg.svgPictureStringDecoder
package:flutter_svg/svg.dart:90
<asynchronous suspension>
Picture provider: ExactAssetPicture(name: "packages[/flag/res/4x3/pe.svg]()", bundle: null, colorFilter: null)
Picture key: AssetBundlePictureKey(bundle: PlatformAssetBundle#d1b8c(), name: "packages[/flag/res/4x3/pe.svg]()", colorFilter: null, theme: SvgTheme(currentColor: null, fontSize: 14.0, xHeight: 7.0))

**Comment by LunaGao** [comment]
fixed.
![image](https://github.com/LunaGao/flag_flutter/assets/5066920/2d91b120-b732-40a4-9bd6-bc048f209568)
