### ISSUE TITLE
Update flag_flutter version

### ISSUE THREAD

**Issue by ViachaslauPratasenia** [LunaGao/flag_flutter#79]
Please update the library version so that the changes from https://github.com/LunaGao/flag_flutter/pull/78 get into pub.dev

**Comment by Saifallak** [comment]
@LunaGao kindly checkout this?
we need only pump the version and also update `flutter_svg` package

**Comment by saropa** [comment]
Yes please!!

**Comment by stefanschaller** [comment]
@LunaGao Any news?

**Comment by JiangHongTiao** [comment]
@LunaGao are you working on this? Can we give a hand somehow?

**Comment by stefanschaller** [comment]
@LunaGao  Hello? Do you even care about the open issues? 
I could help you, if you need any help.

**Comment by stefanschaller** [comment]
Is there any option to remove the caching of the svg package, since this issue is not fixed at all: https://github.com/dnfield/flutter_svg/issues/841

**Comment by stefanschaller** [comment]
@ViachaslauPratasenia  @Saifallak  @saropa  Do you need the caching / preload, which is the reason there is currently no fix / new version

**Comment by saropa** [comment]
Good to have but not needed. As this package is not maintained we're looking for alternatives.

> @ViachaslauPratasenia @Saifallak @saropa Do you need the caching / preload, which is the reason there is currently no fix / new version

**Comment by stefanschaller** [comment]
@saropa  Same for my company. We need a stable package that is actively maintained.

**Comment by yelkamel** [comment]
Same for me flutter_svg update dependencies needed

**Comment by stefanschaller** [comment]
https://github.com/LunaGao/flag_flutter/pull/83 @yelkamel  @saropa  Is that working for you?

**Comment by saropa** [comment]
Hi, we sincerely appreciate the PRs. Will do a dep override and see if it works.

**Comment by saropa** [comment]
Works great, so we'll be using your PR until we find a replacement. Thanks again

**Comment by stefanschaller** [comment]
@yelkamel  You just need to add the following code to your dependencies:

```
 flag:
    git:
      url: https://github.com/tappeddev/flag_flutter.git
      ref: stable
```

**Comment by stefanschaller** [comment]
Could be closed

**Comment by saropa** [comment]
thanks you both!

**Comment by LunaGao** [comment]
@stefanschaller Thank you. :)
