### ISSUE TITLE
Several icons fail to load with error: Bad state: Expected to find Drawable with id

### ISSUE THREAD

**Issue by baracuda69** [LunaGao/flag_flutter#82]
ar.svg
gd.svg
ht.svg
lk.svg
mx.svg
pe.svg
rs.svg all fail to load.

Attached are fixed 4x3 icons
[4x3.zip](https://github.com/LunaGao/flag_flutter/files/11531136/4x3.zip)

**Comment by LunaGao** [comment]
already fix in 7.0.0.
![image](https://github.com/LunaGao/flag_flutter/assets/5066920/53d3ae3a-e12e-4f85-84df-9f8ac4679064)
